"""initial migration

Revision ID: d4d4b844d44d
Revises: 
Create Date: 2026-03-07 03:43:14.429387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d4b844d44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_staffs',
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('Doctor', 'Nurse', 'Receptionist', 'Admin'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=False),
    sa.Column('alternate_no', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('aadhar_no', sa.String(length=12), nullable=False),
    sa.Column('pan_no', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('aadhar_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pan_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_staffs')
    # ### end Alembic commands ###
